
#eureka:
#  client:
#    register-with-eureka: false
#server:
#  port: 9000
spring:
  application:
    name: gateway
  config:
    import: optional:configserver:http://localhost:8888
#  cloud:
#    gateway:
#      discovery:
#        locator:
#          enabled: true
#      routes:
#        - id: testtype
#          uri: http://localhost:8082
#          predicates:
#            - Path=/api/v1/TestType/**
#        - id: standardtest
#          uri: http://localhost:8070
#          predicates:
#            - Path=/api/v1/StandardTest/**
#        - id: patients
#          uri: http://localhost:8090
#          predicates:
#            - Path=/api/v1/Patient/**
#  swagger-ui:
#    path: /swagger-ui.html