eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 8070
spring:
  application:
    name: standardtest
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/standardtest
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
      generate-ddl: true
      show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
  swagger-ui:
  path: /swagger-ui.html
